### ISSUE TITLE
목록보기_전체_View 만들기

### ISSUE THREAD

**Issue by akrudal** [akrudal/Recody_front#12]
### 📃 Description
다음 화면을 만든다. 기록추가 버튼을 누르면 나오는 것 같다.
<img width="245" alt="image" src="https://user-images.githubusercontent.com/62610032/187862117-82c1faad-9a3e-48a7-9620-0c1cba1e5dc6.png">

장르 탭 밑으로 스크롤이 이루어져야하며, 장르 탭끼리 가로로 슬라이드가 이루어져야한다.
따라서 collectionView 안에 collectionView를 만들것이다.

### ✔ Todo
- [ ] searchBar 구현하기
- [ ] Category뷰를 재사용하기
- [ ] genre collectionView 만들기
- [ ] genre collectionView header에 가로로 스크롤되는 genre 탭들 넣기
- [ ] work collectionView 만들기
- [ ] work collectionView header에 dropdown 만들기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 16시간
