### ISSUE TITLE
commit template 적용하기

### ISSUE THREAD

**Issue by akrudal** [akrudal/Recody_front#2]
### 📃 Description
commit template을 만들고 적용하여, 두 번째 commit을 날린다.

### ✔ Todo
- [ ] commit convention 생각하기
- [ ] commit template 작성하기
- [ ] PR과 commit 연결하기

### 🔴 ETC
예상 기간: 1일
