### ISSUE TITLE
Home View 만들기

### ISSUE THREAD

**Issue by akrudal** [akrudal/Recody_front#4]
### 📃 Description

Home 화면의 와이어프레임이 나왔다.
다음 화면을 대략적으로 storyboard에 표현한다.

![image](https://user-images.githubusercontent.com/62610032/183403709-9c5a5f1d-08b5-4669-b4a0-befb6ff42996.png)

### ✔ Todo
- [ ] Home.storyboard 생성하기
- [ ] TabBarController 생성하기
- [ ] Home.storyboard 파일에 AutoLayout 적용하기
- [ ] font 및 color 색상 지정하기

### 🔴 ETC
예상 개발 기간: 6시간
